# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cryption.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cryption.proto',
  package='basicIM',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63ryption.proto\x12\x07\x62\x61sicIM\"8\n\x08\x63ryption\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\x0c\n\x04hmac\x18\x03 \x01(\x0c\x12\n\n\x02IV\x18\x04 \x01(\x0c')
)




_CRYPTION = _descriptor.Descriptor(
  name='cryption',
  full_name='basicIM.cryption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ciphertext', full_name='basicIM.cryption.ciphertext', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hmac', full_name='basicIM.cryption.hmac', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IV', full_name='basicIM.cryption.IV', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['cryption'] = _CRYPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cryption = _reflection.GeneratedProtocolMessageType('cryption', (_message.Message,), {
  'DESCRIPTOR' : _CRYPTION,
  '__module__' : 'cryption_pb2'
  # @@protoc_insertion_point(class_scope:basicIM.cryption)
  })
_sym_db.RegisterMessage(cryption)


# @@protoc_insertion_point(module_scope)
